<?php 
add_action('init', function() {
    if (function_exists('acf_add_options_page')) {
        $marketing_page = acf_add_options_page([
            'page_title' 	=> 'Marketing',
            'menu_title' 	=> 'Marketing',
            'menu_slug' 	=> 'marketing',
            'position' 		=> 75,
            'capability' 	=> 'update_core',
            'icon_url' 		=> 'dashicons-randomize',
            'redirect' 		=> false
        ]);
    }

    if (function_exists('acf_add_local_field_group')) {
        // Set up Marketing options

        acf_add_local_field_group(array(
            'key' => 'group_6228c1ad231ee',
            'title' => 'Marketing Options',
            'fields' => array(
                array(
                    'key' => 'field_6228d3c185bbd',
                    'label' => 'Google Analytics',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_6228d3cd85bbe',
                    'label' => 'Google Analytics',
                    'name' => 'google_analytics',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
                array(
                    'key' => 'field_6228d3a685bbc',
                    'label' => 'Schema',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                // start schema
                array(
                    'key' => 'field_635954c087903',
                    'label' => 'Schema Script',
                    'name' => 'schema_script',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Schema Script',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6228c1b1f5b45',
                            'label' => 'Schema Type',
                            'name' => 'schema_type',
                            'type' => 'text',
                            'instructions' => 'Leave blank to use the default "LocalBusiness"',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_6228c1bds1f5b45',
                            'label' => 'Schema Name',
                            'name' => 'schema_name',
                            'type' => 'text',
                            'instructions' => 'Leave blank to use the site title',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_6228cfs1bds1f5b45',
                            'label' => 'Schema Branch Of',
                            'name' => 'schema_branch_of',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_6228c36ef5b46',
                            'label' => 'Schema Image',
                            'name' => 'schema_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_6228c51bf5b47',
                            'label' => 'Schema Address',
                            'name' => 'schema_address',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6228c559f5b48',
                                    'label' => 'streetAddress',
                                    'name' => 'streetaddress',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6228c5fbf5b49',
                                    'label' => 'addressLocality',
                                    'name' => 'addresslocality',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6228c60bf5b4a',
                                    'label' => 'addressRegion',
                                    'name' => 'addressregion',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6228c617f5b4b',
                                    'label' => 'postalCode',
                                    'name' => 'postalcode',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6228c635f5b4c',
                            'label' => 'Schema Telephone',
                            'name' => 'schema_telephone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_6228c655f5b4d',
                            'label' => 'Schema Opening Hours',
                            'name' => 'schema_opening_hours',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_6232f4e96259f',
                                        'operator' => '!=',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6232f29e2ef3d',
                                    'label' => 'Days',
                                    'name' => 'days',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'mon' => 'Monday',
                                        'tues' => 'Tuesday',
                                        'weds' => 'Wednesday',
                                        'thurs' => 'Thursday',
                                        'fri' => 'Friday',
                                        'sat' => 'Saturday',
                                        'sun' => 'Sunday',
                                    ),
                                    'allow_custom' => 0,
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                    'return_format' => 'label',
                                    'save_custom' => 0,
                                ),
                                array(
                                    'key' => 'field_6232f2e42ef3e',
                                    'label' => 'Opening Time',
                                    'name' => 'opening_time',
                                    'type' => 'time_picker',
                                    'instructions' => '24 hour clock, format 00:00',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'display_format' => 'H:i',
                                    'return_format' => 'H:i',
                                ),
                                array(
                                    'key' => 'field_6232f3162ef3f',
                                    'label' => 'Closing Time',
                                    'name' => 'closing_time',
                                    'type' => 'time_picker',
                                    'instructions' => '24 hour clock, format 00:00',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'display_format' => 'H:i',
                                    'return_format' => 'H:i',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6232f4e96259f',
                            'label' => 'Schema Opening 24 Hrs',
                            'name' => 'schema_opening_24_hrs',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                          'key' => 'field_6228dc635f5b4c',
                          'label' => 'Schema Email',
                          'name' => 'schema_email',
                          'type' => 'text',
                          'instructions' => 'Leave blank to use email from site options.',
                          'required' => 0,
                          'conditional_logic' => 0,
                          'wrapper' => array(
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'default_value' => '',
                          'placeholder' => '',
                          'prepend' => '',
                          'append' => '',
                          'maxlength' => '',
                        ),
                        array(
                          'key' => 'field_622d8dc635f5b4c',
                          'label' => 'VAT Number',
                          'name' => 'vat_number',
                          'type' => 'text',
                          'instructions' => 'Leave blank to use VAT number from site options.',
                          'required' => 0,
                          'conditional_logic' => 0,
                          'wrapper' => array(
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'default_value' => '',
                          'placeholder' => '',
                          'prepend' => '',
                          'append' => '',
                          'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_6228c7b0f5b4f',
                            'label' => 'Schema SameAs',
                            'name' => 'schema_sameas',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6228c7bef5b50',
                                    'label' => 'sameAs',
                                    'name' => 'sameas',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6228c83ef5b51',
                            'label' => 'Schema Description',
                            'name' => 'schema_description',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_6228c87ef5b52',
                            'label' => 'Schema Areas Served',
                            'name' => 'schema_areas_served',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6228c941f5b54',
                                    'label' => 'Type',
                                    'name' => 'type',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6228c946f5b55',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6228c94af5b56',
                                    'label' => 'ID',
                                    'name' => 'id',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                ),
                //end schema
                array(
                    'key' => 'field_6228d3f785bbf',
                    'label' => 'Meta Tags',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_6228d41585bc0',
                    'label' => 'Meta Tags',
                    'name' => 'meta_tags',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'marketing',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
});
